-- SPDX-FileCopyrightText: Iridesium
-- SPDX-License-Identifier: GPL-3.0-only
--
-- Every block Spindle places, one per layer, with a flat placeholder texture.
--
-- The point of this pass is to be able to fly through the world and SEE the
-- layers, so each one gets its own colour and nothing more. Real textures,
-- sounds and hardness are a later pass; the ids are what the rest of the mod
-- depends on and they do not change.
--
-- `textures/*.png` are generated by ../../tools/make_textures.py from the
-- colours in that script — edit it there, not by hand.

local M = {}

-- Footsteps come from the core reference set: a qualified id is used as-is.
local STEP = { step = "core:step" }

local function block(id, name, description, extra)
    local spec = {
        id = id,
        name = name,
        description = description,
        textures = { all = "textures/" .. id .. ".png" },
        sounds = STEP,
    }
    if extra then
        for key, value in pairs(extra) do
            spec[key] = value
        end
    end
    -- `register_block` hands back the per-session numeric id, which is what
    -- the native fills take. Never persisted, never compared to a literal.
    M[id] = game.register_block(spec)
    return M[id]
end

-- Surface ---------------------------------------------------------------
block("stone", "Stone", "The body of the world.", { hardness = 1.5 })
block("dirt", "Dirt", "Ground with no biome claim on it yet.", { hardness = 0.5 })
block("grass", "Grass", "Temperate turf.", { hardness = 0.5 })
block("oak_log", "Oak log", "Trunk of a temperate oak.", { hardness = 1.0 })
block("oak_leaves", "Oak leaves", "Canopy of a temperate oak.", { hardness = 0.2 })

-- Depth bands -----------------------------------------------------------
block("gloam_stone", "Gloam stone", "Dark-cave rock, 1.6 to 4 km down.", { hardness = 2.0 })
block("abyss_stone", "Abyss stone", "Pressure-crushed rock, below 4 km.", { hardness = 3.0 })

-- The magma shell: a thin lava layer with a crust on each side ----------
block("magma_crust", "Magma crust", "Cooked rock, fifty blocks either side of the fire.", { hardness = 2.5 })
block("magma", "Magma", "Still lava. A look-alike solid until fluid can be generated.",
    { hardness = 4.0, light_emit = { r = 15, g = 7, b = 0 } })

-- The core stack --------------------------------------------------------
block("lantern_stone", "Lantern stone", "Hot magical caves: it glows.",
    { hardness = 2.0, light_emit = { r = 10, g = 8, b = 4 } })
block("caul", "Caul", "The slime border: a luminous membrane.",
    { hardness = 0.8, light_emit = { r = 4, g = 9, b = 3 } })
block("dream_stone", "Dream stone", "Cold magical caves: ice-lit.",
    { hardness = 2.0, light_emit = { r = 3, g = 5, b = 9 } })
block("scorch", "Scorch", "The hollow ring: dense, hot, dry.", { hardness = 3.5 })

-- The tail --------------------------------------------------------------
block("marrow", "Marrow", "White porous stone of the tail.", { hardness = 1.2 })
block("apex_stone", "Apex stone", "What the needle is made of at the end.", { hardness = 5.0 })

game.log("spindle: registered placeholder blocks")

return M
